[cmd_duration]
min_time = 1

[directory]
fish_style_pwd_dir_length = 1

[git_status]
show_sync_count = true
modified = "*"

[nix_shell]
impure_msg = "nix-shell"
pure_msg = "nix-shell (pure)"

[rust]
disabled = true
[golang]
disabled = true
[ruby]
disabled = true
[nodejs]
disabled = true
[python]
disabled = true

