prompt_order = [
    "username",
    "hostname",
    "directory",
    "git_branch",
    "git_state",
    "git_status",
    "package",
    "nodejs",
    "ruby",
    "rust",
    "python",
    "golang",
    "cmd_duration",
    "line_break",
    "jobs",
    "battery",
    "nix_shell",
    "character",
]

[cmd_duration]
min_time = 1

[directory]
fish_style_pwd_dir_length = 1

[git_status]
show_sync_count = true
modified = "*"

[nix_shell]
impure_msg = "λ"
pure_msg = "λλ"

[rust]
disabled = true
[golang]
disabled = true
[ruby]
disabled = true
[nodejs]
disabled = true
[python]
disabled = true

